#!/bin/sh

SIDECAR_LOG_LEVEL="debug"
SERVICE_MYSQL_USER="root"
SERVICE_MYSQL_PASS="root123"
SERVICE_MYSQL_PORT="3306"
SIDECAR_DEV_MODE="true"

if [ ! -z ${DOCKER_HOST} ]
then
    export DOCKER_HOST_IP=`echo ${DOCKER_HOST} | cut -d "/" -f 3 | cut -d ":" -f 1`
else
    export DOCKER_HOST_IP=`ip route get 8.8.8.8 | awk 'NR==1 {print $NF}'`
fi

docker run --name ${SIDECAR_EXTENSION_IMAGE_NAME} \
	-p 0.0.0.0:${SIDECAR_EXTENSION_PORT}:8081 \
	-e SERVICE_MYSQL_USER=${SERVICE_MYSQL_USER} \
	-e SERVICE_MYSQL_PASS=${SERVICE_MYSQL_PASS} \
	-e SERVICE_MYSQL_HOST=${DOCKER_HOST_IP} \
	-e SERVICE_MYSQL_PORT=${SERVICE_MYSQL_PORT} \
	-e SIDECAR_LOG_LEVEL=${SIDECAR_LOG_LEVEL} \
	-e SIDECAR_API_KEY=${SIDECAR_API_KEY} \
	-e SIDECAR_DEV_MODE=${SIDECAR_DEV_MODE} \
	-d ${SIDECAR_EXTENSION_IMAGE_NAME}:${SIDECAR_EXTENSION_IMAGE_TAG}
