FROM cf-usb-sidecar-buildbase:latest

COPY . /go/src/github.com/SUSE/cf-usb-sidecar/csm-extensions/services/dev-rabbitmq
ENV GOPATH /go
ENV GOBIN /go/bin
WORKDIR /go/src/github.com/SUSE/cf-usb-sidecar/csm-extensions/services/dev-rabbitmq

RUN make tools
RUN make build

ENTRYPOINT cp -r /go/src/github.com/SUSE/cf-usb-sidecar/csm-extensions/services/dev-rabbitmq/SIDECAR_HOME/* /out/