ARG base_image=opensuse/leap:latest

FROM ${base_image}

ARG hub_version=2.3.0-pre10

# If we're on the SLE container, delete the magic helper for SCC registration
# It just slows down zypper
RUN if test -e /usr/lib/zypp/plugins/services/container-suseconnect ; then \
        rpm --erase container-suseconnect ; \
    fi

ARG repo_cloud_tools=obs://Cloud:Tools
ARG repo_devel_languages_go=obs://devel:languages:go
ARG repo_extra
# Useless command to _use_ the args, which somehow makes things work. Not sure why.
RUN set -o errexit -o nounset -o xtrace \
    ; zypper --non-interactive addrepo --check --gpgcheck "${repo_cloud_tools}" "Cloud:Tools" \
    ; zypper --non-interactive addrepo --check --gpgcheck "${repo_devel_languages_go}" "devel:languages:go" \
    ; if test -n "${repo_extra}" ; then \
        zypper --non-interactive addrepo --check --gpgcheck "${repo_extra}" "extra" \
    ; fi \
    ; zypper --non-interactive --gpg-auto-import-keys refresh \
    ; zypper --non-interactive install \
        cf-cli \
        git \
        gzip \
        go \
        make \
        tar \
        unzip \
        wget \
    ; true

RUN mkdir /out

RUN cp /usr/bin/cf /out

RUN wget -O /out/cf-usb-plugin https://github.com/SUSE/cf-usb-plugin/releases/download/1.0.0/cf-usb-plugin-1.0.0.0.g47b49cd-linux-amd64
RUN chmod +x /out/cf-usb-plugin

# "hub" CLI, https://hub.github.com/hub.1.html
# Used to create PRs for helm chart distribution
RUN wget -O - https://github.com/github/hub/releases/download/v${hub_version}/hub-linux-amd64-${hub_version}.tgz | tar xvz -C /usr/local/bin --wildcards --strip-components=2 '*/bin/hub'

COPY . /go/src/github.com/SUSE/cf-usb-sidecar

WORKDIR /go/src/github.com/SUSE/cf-usb-sidecar

RUN make tools

ENTRYPOINT echo `hostname`
