ARG base_image=opensuse:latest

FROM ${base_image}

# If we're on the SLE container, delete the magic helper for SCC registration
# It just slows down zypper
RUN if test -e /usr/lib/zypp/plugins/services/container-suseconnect ; then \
        rpm --erase container-suseconnect ; \
    fi

ARG repo_cloud_tools=obs://Cloud:Tools
ARG repo_devel_languages_go=obs://devel:languages:go
ARG repo_extra
RUN zypper --non-interactive addrepo --check --gpgcheck "${repo_cloud_tools}" "Cloud:Tools"
RUN zypper --non-interactive addrepo --check --gpgcheck "${repo_devel_languages_go}" "devel:languages:go"
RUN if test -n "${repo_extra}" ; then \
    zypper --non-interactive addrepo --check --gpgcheck "${repo_extra}" "extra" ; \
    fi
RUN zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive install \
    cf-cli \
    git \
    go \
    make \
    tar \
    unzip \
    wget \
    ${NULL}

RUN mkdir /out

RUN cp /usr/bin/cf /out

RUN wget -O cf-plugin-usb.zip https://github.com/SUSE/cf-usb-plugin/releases/download/0.0.1/cf-plugin-usb-linux-amd64.zip
RUN unzip cf-plugin-usb.zip
RUN mv cf-plugin-usb /out
RUN chmod +x /out/cf-plugin-usb

# "hub" CLI, https://hub.github.com/hub.1.html
# Used to create PRs for helm chart distribution
RUN wget -O - https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-amd64-2.3.0-pre10.tgz | tar xvz -C /usr/local/bin --wildcards --strip-components=2 '*/bin/hub'

COPY . /go/src/github.com/SUSE/cf-usb-sidecar

WORKDIR /go/src/github.com/SUSE/cf-usb-sidecar

RUN make tools

ENTRYPOINT echo `hostname`
