ARG base_image=opensuse:latest

FROM ${base_image}

RUN zypper --non-interactive addrepo --check --gpgcheck obs://Cloud:Tools Cloud:Tools
RUN zypper --non-interactive addrepo --check --gpgcheck obs://devel:languages:go devel:languages:go
RUN zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive install \
    cf-cli \
    git \
    go \
    make \
    unzip \
    wget \
    ${NULL}

RUN mkdir /out

RUN cp /usr/bin/cf /out

RUN wget -O cf-plugin-usb.zip https://github.com/SUSE/cf-usb-plugin/releases/download/0.0.1/cf-plugin-usb-linux-amd64.zip
RUN unzip cf-plugin-usb.zip
RUN mv cf-plugin-usb /out
RUN chmod +x /out/cf-plugin-usb

COPY . /go/src/github.com/SUSE/cf-usb-sidecar

WORKDIR /go/src/github.com/SUSE/cf-usb-sidecar

RUN make tools

ENTRYPOINT echo `hostname`
