---
# The mysql role contains a plain mysql server (mysql 5.5)
{{ if eq ( .Values.env.SERVICE_MYSQL_HOST | quote ) ( "AUTO" | quote ) }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "mysql"
  labels:
    skiff-role-name: "mysql"
spec:
  replicas: 1
  serviceName: "mysql-set"
  template:
    metadata:
      name: "mysql"
      labels:
        skiff-role-name: "mysql"
    spec:
      containers:
      - env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "service-mysql-pass"
              name: "cf-usb-sidecar-mysql-secret"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/cf-usb-sidecar-mysql-db:latest"
        readinessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 3306
        name: "mysql"
        ports:
        - containerPort: 3306
          name: "mysql"
          protocol: "TCP"
        resources:
          requests:
            memory: 100M
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "mysql-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "mysql"
      port: 3306
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "mysql"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "mysql"
  spec:
    ports:
    - name: "mysql"
      port: 3306
      protocol: "TCP"
      targetPort: "mysql"
    selector:
      skiff-role-name: "mysql"
    type: "ClusterIP"
kind: "List"

{{ end }}
