FROM sidecar-buildbase:latest

ENV GOPATH /go
ENV GOBIN /go/bin

COPY . /go/src/github.com/hpcloud/catalog-service-manager

RUN cd /go/src/github.com/hpcloud/catalog-service-manager \
    && make all

ENTRYPOINT cp /go/bin/catalog-service-manager /catalog-service-manager-bin/
