FROM opensuse:42.3

RUN mkdir -p /catalog-service-manager/bin \
    /catalog-service-manager/setup/startup \
    /catalog-service-manager/setup/shutdown \

    /catalog-service-manager/workspace/get \
    /catalog-service-manager/workspace/create \
    /catalog-service-manager/workspace/delete \

    /catalog-service-manager/connection/get \
    /catalog-service-manager/connection/create \
    /catalog-service-manager/connection/delete

COPY SIDECAR_BIN/catalog-service-manager /catalog-service-manager/bin/

COPY docs/package-files/* /usr/share/doc/stackato/

ENTRYPOINT ["/catalog-service-manager/bin/catalog-service-manager"]
