FROM hsm-sidecar-buildbase:latest

COPY . /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mssql
ENV GOPATH /go
ENV GOBIN /go/bin
WORKDIR /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mssql

RUN make tools
RUN make build
ENTRYPOINT cp -r /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mssql/SIDECAR_HOME/* /out/
