FROM hsm-sidecar-buildbase:latest

COPY . /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-postgres
ENV GOPATH /go
ENV GOBIN /go/bin
WORKDIR /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-postgres

RUN make tools
RUN make build
ENTRYPOINT cp -r /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-postgres/SIDECAR_HOME/* /out/