FROM sidecar-buildbase:latest

COPY . /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mongo
ENV GOPATH /go
ENV GOBIN /go/bin
WORKDIR /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mongo

RUN make tools
RUN make build

ENTRYPOINT cp -r /go/src/github.com/hpcloud/catalog-service-manager/csm-extensions/services/dev-mongo/SIDECAR_HOME/* /out/