---
apiVersion: "v1"
data:
  # The password for access to the configured postgres database.
  service-postgres-pass: {{ template "getvar" (dict "ctx" . "names" (list "PGPASSWORD" "SERVICE_POSTGRESQL_PASS") "b64" true) }}

  # The token for sidecar access by the cf-usb role in SCF.
  sidecar-api-key: {{ randAlphaNum 32 | b64enc | quote }}

  # The PEM-encoded SCF CA certificate used to sign the TLS
  # certificate required by the cf client in the setup task to secure
  # the communication with the api endpoint.
  cf-ca-cert: {{ template "getvar" (dict "ctx" . "names" (list "CF_CA_CERT") "b64" true) }}

  # The PEM-encoded UAA CA certificate
  uaa-ca-cert: {{ template "getvar" (dict "ctx" . "names" (list "UAA_CA_CERT") "b64" true) }}

  # Cluster password
  cf-admin-password: {{ template "getvar" (dict "ctx" . "names" (list "CF_ADMIN_PASSWORD") "b64" true) }}

kind: "Secret"
metadata:
  name: "cf-usb-sidecar-postgres-secret"
  labels:
    skiff-role-name: "cf-usb-sidecar-postgres-secret"
