FROM cf-usb-sidecar-buildbase:latest

COPY chart/scf-connector.sh /
WORKDIR /

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y unzip
RUN wget -O cf.tar.gz 'https://cli.run.pivotal.io/stable?release=linux64-binary&source=github' \
    && tar xf cf.tar.gz \
    && rm cf.tar.gz LICENSE NOTICE \
    && wget -O cf-plugin-usb.zip https://github.com/SUSE/cf-usb-plugin/releases/download/0.0.1/cf-plugin-usb-linux-amd64.zip \
    && /usr/bin/unzip cf-plugin-usb.zip \
    && rm cf-plugin-usb.zip

RUN chmod +x /cf /cf-plugin-usb /scf-connector.sh

ENTRYPOINT /bin/bash /scf-connector.sh
