FROM cf-usb-sidecar-buildbase:latest

COPY chart/scf-connector.sh /usr/local/bin/
WORKDIR /

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y unzip


RUN wget -O -  'https://cli.run.pivotal.io/stable?release=linux64-binary&source=github' | tar xfz - -C /usr/local/bin cf \
    && wget -O cf-plugin-usb.zip https://github.com/SUSE/cf-usb-plugin/releases/download/0.0.1/cf-plugin-usb-linux-amd64.zip \
    && /usr/bin/unzip cf-plugin-usb.zip \
    && mv cf-plugin-usb /usr/local/bin \
    && rm cf-plugin-usb.zip

RUN chmod +x /usr/local/bin/cf /usr/local/bin/cf-plugin-usb /usr/local/bin/scf-connector.sh

ENTRYPOINT /bin/bash /usr/local/bin/scf-connector.sh
