FROM cf-usb-sidecar-buildbase:latest as builder

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y unzip
RUN mkdir /out
RUN wget -O cf.tgz 'https://cli.run.pivotal.io/stable?release=linux64-binary'
RUN tar xzf cf.tgz -C /out cf
RUN wget -O cf-plugin-usb.zip https://github.com/SUSE/cf-usb-plugin/releases/download/0.0.1/cf-plugin-usb-linux-amd64.zip
RUN unzip cf-plugin-usb.zip
RUN mv cf-plugin-usb /out
COPY chart/scf-connector.sh /out/
COPY chart/authorize_ca.sh  /out/
RUN chmod +x /out/cf /out/cf-plugin-usb /out/scf-connector.sh

FROM cf-usb-sidecar-buildbase:latest
COPY --from=builder /out/ /usr/local/bin/
WORKDIR /
ENTRYPOINT /bin/bash /usr/local/bin/scf-connector.sh
COPY --from=builder /out/ /usr/local/bin/
