#!/bin/sh

PORT="4446"

docker run --privileged \
	--name ${SIDECAR_EXTENSION_SVC_CONTAINER_NAME} \
	-p ${SIDECAR_EXTENSION_SVC_PORTS_START}-${SIDECAR_EXTENSION_SVC_PORTS_END}:${SIDECAR_EXTENSION_SVC_PORTS_START}-${SIDECAR_EXTENSION_SVC_PORTS_END} \
	-p ${PORT}:2375 \
	-d ${SIDECAR_EXTENSION_SVC_IMAGE_NAME}:${SIDECAR_EXTENSION_SVC_IMAGE_TAG}
