#!/bin/sh

MONGODB_PASS="password"
MONGODB_PORT="27017"

docker run --name ${CSM_EXTENSION_SVC_CONTAINER_NAME} -e MONGODB_PASS=${MONGODB_PASS} -p ${MONGODB_PORT}:${MONGODB_PORT} -d ${CSM_EXTENSION_SVC_IMAGE_NAME}:${CSM_EXTENSION_SVC_IMAGE_TAG}
