#!/bin/sh

MONGODB_PASS="password"
MONGODB_PORT="27017"

docker run --name ${SIDECAR_EXTENSION_SVC_IMAGE_NAME} -e MONGODB_PASS=${MONGODB_PASS} -p ${MONGODB_PORT}:${MONGODB_PORT} -d ${SIDECAR_EXTENSION_SVC_IMAGE_NAME}:${SIDECAR_EXTENSION_SVC_IMAGE_TAG}
