#!/bin/sh

SERVICE_MONGO_USER="admin"
SERVICE_MONGO_PASS="password"
SERVICE_MONGO_PORT="27017"
SIDECAR_LOG_LEVEL="debug"
SIDECAR_DEV_MODE="true"
SIDECAR_API_KEY=${SIDECAR_EXTENSION_TOKEN}

if [ ! -z ${DOCKER_HOST} ]
then
    export DOCKER_HOST_IP=`echo ${DOCKER_HOST} | cut -d "/" -f 3 | cut -d ":" -f 1`
else
    export DOCKER_HOST_IP=`ip route get 8.8.8.8 | awk 'NR==1 {print $NF}'`
fi


docker run --name ${SIDECAR_EXTENSION_IMAGE_NAME} \
	-p 8092:8081 \
	-e SERVICE_MONGO_USER=${SERVICE_MONGO_USER} \
	-e SERVICE_MONGO_PASS=${SERVICE_MONGO_PASS} \
	-e SERVICE_MONGO_HOST=${DOCKER_HOST_IP} \
	-e SERVICE_MONGO_PORT=${SERVICE_MONGO_PORT} \
	-e SIDECAR_LOG_LEVEL=${SIDECAR_LOG_LEVEL} \
	-e SIDECAR_API_KEY=${SIDECAR_API_KEY} \
	-e SIDECAR_DEV_MODE=${SIDECAR_DEV_MODE} \
	-d ${SIDECAR_EXTENSION_IMAGE_NAME}:${SIDECAR_EXTENSION_IMAGE_TAG}
