#!/bin/sh

SERVICE_POSTGRES_USER="postgres"
SERVICE_POSTGRES_PASSWORD="password"
SERVICE_POSTGRES_PORT="5432"
SERVICE_POSTGRES_DBNAME="postgres"
SERVICE_POSTGRES_SSLMODE="disable"
CSM_LOG_LEVEL="debug"
CSM_DEV_MODE="true"
CSM_API_KEY="csm-auth-token"



if [ ! -z ${DOCKER_HOST} ]
then
    export DOCKER_HOST_IP=`echo ${DOCKER_HOST} | cut -d "/" -f 3 | cut -d ":" -f 1`
else
    export DOCKER_HOST_IP=`ip route get 8.8.8.8 | awk 'NR==1 {print $NF}'`
fi


docker run --name ${CSM_EXTENSION_IMAGE_NAME} \
	-p 0.0.0.0:8093:8081 \
	-e SERVICE_POSTGRES_USER=${SERVICE_POSTGRES_USER} \
	-e SERVICE_POSTGRES_PASSWORD=${SERVICE_POSTGRES_PASSWORD} \
	-e SERVICE_POSTGRES_HOST=${DOCKER_HOST_IP} \
	-e SERVICE_POSTGRES_PORT=${SERVICE_POSTGRES_PORT} \
	-e SERVICE_POSTGRES_DBNAME=${SERVICE_POSTGRES_DBNAME} \
	-e SERVICE_POSTGRES_SSLMODE=${SERVICE_POSTGRES_SSLMODE} \
	-e CSM_LOG_LEVEL=${CSM_LOG_LEVEL} \
	-e CSM_API_KEY=${CSM_API_KEY} \
	-e CSM_DEV_MODE=${CSM_DEV_MODE} \
	-d ${CSM_EXTENSION_IMAGE_NAME}:${CSM_EXTENSION_IMAGE_TAG}
