#!/bin/sh

POSTGRES_PASSWORD="password"
POSTGRES_PORT="5432"

docker run --name ${SIDECAR_EXTENSION_SVC_IMAGE_NAME} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -p 0.0.0.0:${POSTGRES_PORT}:${POSTGRES_PORT} -d ${SIDECAR_EXTENSION_SVC_IMAGE_NAME}:${SIDECAR_EXTENSION_SVC_IMAGE_TAG}
