#!/bin/sh

CSM_IMAGE_NAME="csm-mysql:latest"
MYSQL_ROOT_PASSWORD="root123"
CSM_LOG_LEVEL="debug"
MYSQL_SERVICE_PORT_MYSQL="3306"

docker run --name csm-mysql-db -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -p ${MYSQL_SERVICE_PORT_MYSQL}:${MYSQL_SERVICE_PORT_MYSQL} -d mysql:5.5
