package common

var PROCESSING_TYPE_NONE = "none"
var PROCESSING_TYPE_DEFAULT = "default"
var PROCESSING_TYPE_EXTENSION = "extension"

var PROCESSING_STATUS_NONE = "none"
var PROCESSING_STATUS_UNKNOWN = "unknown"
var PROCESSING_STATUS_SUCCESSFUL = "successful"
var PROCESSING_STATUS_FAILED = "failed"

var NO_MESSAGE = ""
