package common

var PROCESSING_TYPE_NONE = "None"
var PROCESSING_TYPE_DEFAULT = "Default"
var PROCESSING_TYPE_EXTENSION = "Extension"

var PROCESSING_STATUS_NONE = "None"
var PROCESSING_STATUS_UNKNOWN = "Unknown"
var PROCESSING_STATUS_SUCCESSFUL = "Successful"
var PROCESSING_STATUS_FAILED = "Failed"
