#!/bin/sh

MYSQL_ROOT_PASSWORD="root123"
MYSQL_SERVICE_PORT_MYSQL="3306"

docker run --name csm-mysql-db -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -p ${MYSQL_SERVICE_PORT_MYSQL}:${MYSQL_SERVICE_PORT_MYSQL} -d mysql:5.5
