#!/bin/sh
set -e

{
	sleep 10

	echo "loading docker image ..." > /out.txt
	docker load -i /root/redis.tgz 1>/docker_load_out.txt 2>/docker_load_err.txt
	echo "docker image loaded" >> /out.txt
	
	containers=$(docker ps -q -a)
	
	index=0

        (for c in $containers;
        do
                name=$(docker inspect -f "{{.Name}}" $c | cut -d "/" -f 2)
                port=$(docker inspect -f "{{.HostConfig.PortBindings}}" $c)
                length=$(expr $(expr index "$port" "}") - $(expr index "$port" "{") - 1)
                start=$(expr index "$port" "{")
                mappedPort=${port:$start:$length}
                cmd=$(docker inspect -f "{{.Config.Cmd}}" $c | cut -d "[" -f 2 | cut -d "]" -f 1)
                eval NAMES$index=$(echo \"$name\")
                eval MAPPEDPORTS$index=$(echo \"$mappedPort\")
                eval CMDS$index="$(echo \"$cmd\")"
                echo "Removing old container $name"
                docker rm -f $c
                index=$(($index+1))
	done

[ !-z "$containers" ] &&{
        echo "deleting all images" >> /out.txt
		docker rmi -f $(docker images -q)
        echo "loading new image" >> /out.txt	
		sleep 5
	    docker load -i /root/redis.tgz
		echo "image loaded">>/out.txt
		docker images >> /out.txt
}
        index=0

        for c in $containers;
        do
                name=$(eval echo $"NAMES$index")
                port=$(eval echo $"MAPPEDPORTS$index")
                cmd=$(eval echo \"$"CMDS$index"\")
                echo Creating new container $name
                echo $(eval echo $"MAPPEDPORTS$index")
                echo $(eval echo $"CMDS$index")
                index=$(($index+1))
                echo "creating $name" >> /out.txt
                docker run --name  $name -v /data/$name:/data -p $port:6379 -d redis:hsm $cmd
        done)
} &
dockerd-entrypoint.sh
