#!/bin/sh
set -e

{
    echo "sleeping for 5 seconds"
    sleep 5
    docker load -i /root/redis.tgz
} &

{
   for i in `seq 1 10`; 
   do
     sleep 60;
     docker ps -a -q| xargs -n 1 docker start;
   done 
} &

dockerd-entrypoint.sh

